FROM confluentinc/cp-kafka:latest

# Copiar o script para dentro do container
COPY create-topics.sh /usr/bin/create-topics.sh

# Dar permissão de execução ao script como root
USER root
RUN chmod +x /usr/bin/create-topics.sh

# Voltar ao usuário padrão para o Kafka
USER 1001


# Comando para iniciar o Kafka e executar o script
CMD ["sh", "-c", "kafka-server-start /etc/kafka/server.properties & sleep 10 && /usr/bin/create-topics.sh"]
